### ISSUE TITLE
Playing/Install problems

### ISSUE THREAD

**Issue by Fasoldgames** [PhantasarProductions/TFTRevamp#419]
I played the game some more yesterday, but suddenly I was ejected from it. Now it won't start. I have deleted the game and re-installed it, but the Game Jolt client says something went wrong with the installation. Something with the unpacking of the game?

**Comment by Tricky1975** [comment]
Unfortunately it's hard for me to check if this is error is mine or the Game Jolt Client's as the latter is known to malfunction at the present time, so I will need to have a chat with the Game Jolt admins.
Does the game work when you install the game manually? (this will require an unpacking program compatible with the 7z file format. Are you familiar with 7z?)

gamejolt/issue-tracker#832

**Comment by Fasoldgames** [comment]
Hi,

The game dropped me out, then the client refused to start the game up
again. I deleted the game and tried
to reinstall, but it did not work. Then I installed the game without
sound, the 2nd package and started a new game...but during
the compiling I think it is? it dropped me again and the client refused to
start the game again.

I'll try to start it up again later.

Best regards,

Fabian

**Comment by Tricky1975** [comment]
Ah, wait... now this is interesting. Can you try to run the game manually (in the client settings you can see where the games are stored), and if it drops out again, can you show me any screenshot of any error messages (you can just use print screen and then paste them in this issue tracker), as now some confusion comes to me if there is an error in the game or if this is the client or if this is even both.
The fact that you speak of compiling may mean that something went wrong during the compiling of the scripts....

**Comment by Fasoldgames** [comment]
Hi,

It would not launch, so I installed it again via the game jolt client, but
then I got this
message:

 'Oh no! We couldn't unpack this package after downloading it. Maybe try
again?'

Then the client got all crazy on me so I downloaded the game via the
browser. I downloaded it, ran it, and started a new
game. The game began, but then booted me out. Not only that, but the
Laura2 file and the game execute have been deleted. The folder now only
contains the .jcr files.

I'm using Windows 10 home edition.

Best regards,

Fabian

**Comment by Tricky1975** [comment]
Right that “Oh no!" message is clearly a bug in the client.
Now the deletion of the LAURA2.exe file appears very extremely odd to me and that should not be possible at all, and the only problem I can think of causing this would also destroy the .jcr files. Or is your virus scanner too aggressively thinking my game could be a virus? But even if it did think that I think a proper warning should be in order. Not to mention that Windows does not even allow .exe files to be deleted while they are running, so basically even if I did put in commands trying to delete LAURA2.exe Windows would always block them out. 
As I need a “real” Windows computer to properly test this (I’m on Mac remember) this will be a very time consuming operation, so I hope you have some patience. In the meantime I may ask some friends of mine if they can replicate this one…. :-/

**Comment by Fasoldgames** [comment]
Hi,

I have AVG anti-virus installed. I thought it strange too, but when the
program booted me out, the .exe files where deleted. Not
sure how or why, I am not that knowledgeable of the more complex computer
systems.

Best regards,

Fabian

**Comment by Tricky1975** [comment]
AVG you say? Then we might have found the problem. AVG deems nearly every .exe file not officially approved by Microsoft a virus. It’s one of the most aggressive virus scanners around lately. I hope you don’t mind that I am not going to get my stuff approved by Microsoft, since all I need to do to get that done is pay a lot of cash I don’t have. I’m actually pretty poor… 😢 
Maybe you should deactivate AVG and try this all again. Or maybe you should see if you can configure AVG to greenlight me somehow. Trust me, I won’t put malware in my software. I do have a rep to keep up, you know.

(I also wonder if AVG is the reason the client was malfunctioning on you on this one).



EDIT:
I found [this article](https://support.avg.com/SupportArticleView?l=en&urlName=How-to-restore-or-remove-file-from-the-Virus-Vault) on the AVG website. Perhaps you should check if the game’s .exe files did indeed end up in the virus vault and restore them from there, and perhaps AVG will leave those files alone in the future (you did approve them after all).

EDIT II:
And I also found [this](http://smallbusiness.chron.com/turn-off-false-positive-avg-69481.html). It may help you to prevent trouble like this in the future. If you whitelist GJ with this you should be ok. Game Jolt is very strict on viruses, the slightest suspicion will always be sorted out. ;)

**Comment by Fasoldgames** [comment]
Hi,

I've switched off AVG for the moment and the game works now! Made it into
the dragon cave and all,
and am exploring further!

Best regards,

Fabian

**Comment by Tricky1975** [comment]
Ah, the Dragon Cave… Good luck saving little Jenny.
I’m glad the issue is resolved ;)
And I’m glad I know about this so I can put this in the troubleshooting chapter of the still-to-write manual :)

Oh yeah, when it comes to your own game. Please join us in the [ScreenShot ShowCase](https://gamejolt.com/f/screenshot-showcase/60) and post some screenshots. Hopefully this helps gaining some extra followers ;)
(I’ve had some issues trying to download your game. Connection issues most of all. I’ll try again later) ;)

**Comment by Fasoldgames** [comment]
Hi,

I was playing the introduction with the elven priest, and I have a
question. When in a dungeon or dangerous area, there is the Swords icon
that turns yellow and red, in connection with random encounters?

But are the random encounters infinite, or are they numbered?

Best regards,

Fabian

**Comment by Tricky1975** [comment]
Ah you did figure things out in the right direction.
Yes the swords icons do indeed refer to the random encounters.
Blue = No chance to an encounter at all
Green = Very small chance to a random encounter
Ember (or yellow) = High chance to a random encounter
Red = Random encounter almost unavoidable
The bar always starts blue and will chance color in this order based on the distance you walk.
The random encounters are indeed limited, in most dungeons you only can get 5 per room, but these counters reset each time you leave a dungeon a come back.
The gauge under the swords indicate how many random encounters are left in that room.
You may also have guessed that if the swords bar moves out of the screen you are in a room where no random encounters will happen (of course, bosses are still possible).

**Comment by Fasoldgames** [comment]
Ah, thanks! For a moment there I got a flashback to some older games like
Wizardry, with their
endless random encounter system. Dark memories indeed :)

Glad to know it is not like that!

Best regards,

Fabian

**Comment by Tricky1975** [comment]
We all hate that, so I’ve been working on a system to make it less horrible indeed ;)
